package com.subtlesight.word.util;

import java.util.UUID;

/**
 * 文档节点 ID 生成器。
 * <p>
 * 生成持久化、可重用的节点 ID，确保重载文档时能够重新建立映射。
 * 支持两种策略：
 * - 基于 UUID 的随机 ID（默认）
 * - 基于文档结构路径的确定性 ID（用于重定位）
 * </p>
 */
public final class NodeIdGenerator {

    private NodeIdGenerator() {
    }

    /**
     * 生成随机 UUID 节点 ID。
     */
    public static String randomId() {
        return "node-" + UUID.randomUUID().toString().replace("-", "");
    }

    /**
     * 基于部件路径和结构索引生成确定性 ID。
     * 用于重载文档时重新建立节点映射。
     */
    public static String deterministicId(String partPath, int index) {
        String part = partPath.replace("/", "_").replace(".", "_");
        return "auto-" + part + "-" + index;
    }

    /**
     * 基于段落文本哈希生成稳定 ID（用于匹配）。
     */
    public static String hashBasedId(String text) {
        if (text == null || text.isEmpty()) {
            return randomId();
        }
        return "hash-" + Integer.toHexString(text.hashCode());
    }

    /**
     * 判断节点 ID 是否是自动生成的（用于检测需要重新锚定的节点）。
     */
    public static boolean isAutoGenerated(String nodeId) {
        return nodeId != null && (nodeId.startsWith("auto-") || nodeId.startsWith("hash-"));
    }
}